---

name: Draft release
run-name: Draft release ${{ inputs.next_version }}

on:
  workflow_dispatch:
    inputs:
      next_version:
        required: true
        type: string
        description: 'Version name'

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'
          ssh-key: ${{ secrets.VERSION_BUMP }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Extract current version
        run: |
          echo "VERSION_NUMBER=$(npm view package.json version)" >> GITHUB_OUTPUT
        id: version

      - name: Bump version
        run: |
          git checkout -b release/${{ steps.version.outputs.VERSION_NUMBER }}
          git push
          npm version --no-git-tag-version --no-commit-hooks ${{ inputs.next_version }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "version-bump: release ${{ inputs.next_version }}"
          git push

      - name: Merge develop into main
        run: |
          git checkout release/${{ env.VERSION_NUMBER }}
          git pull
          git merge origin/main
          git push

      - name: Draft release
        run: gh release create $VERSION --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.next_version }}
