---

name: Test Build trigger
run-name: Test Build trigger

on:
  #  push:
  #    branches:
  #      - main
  #        # this list should match the .dockerignore list
  #    paths:
  #      - "src/main/**"
  #      - "pom.xml"
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
#    branches:
#      - 'release/**'

permissions:
  contents: write

jobs:
  job1:
    runs-on: "ubuntu-latest"
    steps:
      - name: Step1
        run: echo ${{ github.branch_name }}
#jobs:
#  job1:
#    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          ref: ${{ github.branch }}
#          ssh-key: ${{ secrets.VERSION_BUMP }}