---

name: Test workflow
run-name: test workflow

on:
  #  push:
  #    branches:
  #      - main
  #        # this list should match the .dockerignore list
  #    paths:
  #      - "src/main/**"
  #      - "pom.xml"
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
#    branches:
#      - 'release/**'

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure git
        run: echo "hello"